### ISSUE TITLE
Request is not defined

### ISSUE THREAD

**Issue by sleungcy** [hirviid/react-redux-fetch#16]
Hi, 

I am getting this error with the requestBuilder class

ReferenceError: Request is not defined
    at requestBuilder (/home/sleungcy/code/go-ui/node_modules/react-redux-fetch/lib/utils/requestBuilder.js:23:14)
    at Object.fetchRequest [as middleware] (/home/sleungcy/code/go-ui/node_modules/react-redux-fetch/lib/middleware/fetchRequest.js:20:85)
    at /home/sleungcy/code/go-ui/node_modules/react-redux-fetch/lib/middleware/index.js:29:18
    at /home/sleungcy/code/go-ui/node_modules/lodash/_createBaseFor.js:17:11
    at baseForOwn (/home/sleungcy/code/go-ui/node_modules/lodash/_baseForOwn.js:13:20)

I am using the version published to npm, did I do something wrong?

Thanks,
Sam

**Comment by sleungcy** [comment]
Hi, I figured global.Request is not available in node. I am going to close this now

**Comment by hirviid** [comment]
I think you can polyfill Request and Fetch with e.g. https://github.com/matthew-andrews/isomorphic-fetch
